/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tfg_tfg_Wrapper_CubiomesWrapper */

#ifndef _Included_com_tfg_tfg_Wrapper_CubiomesWrapper
#define _Included_com_tfg_tfg_Wrapper_CubiomesWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tfg_tfg_Wrapper_CubiomesWrapper
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tfg_tfg_Wrapper_CubiomesWrapper_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_tfg_tfg_Wrapper_CubiomesWrapper
 * Method:    setupSeed
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_tfg_tfg_Wrapper_CubiomesWrapper_setupSeed
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_tfg_tfg_Wrapper_CubiomesWrapper
 * Method:    findNearestStructure
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_tfg_tfg_Wrapper_CubiomesWrapper_findNearestStructure
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_tfg_tfg_Wrapper_CubiomesWrapper
 * Method:    getBiomeAt
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_tfg_tfg_Wrapper_CubiomesWrapper_getBiomeAt
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_tfg_tfg_Wrapper_CubiomesWrapper
 * Method:    findNearestBiome
 * Signature: (IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_tfg_tfg_Wrapper_CubiomesWrapper_findNearestBiome
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
