version: '3.9'

services:
  frontend:
    image: nginx:stable-alpine
    container_name: tfg_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - minecraft_network

networks:
  minecraft_network:
    external: true
