version: '3.9'

services:
  frontend:
    build:
      context: .
    container_name: tfg_frontend
    ports:
      - "3000:80"
    networks:
      - minecraft_network

networks:
  minecraft_network:
    external: true