version: '3.9'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: pingu
      POSTGRES_PASSWORD: miausita25
      POSTGRES_DB: minecraft_project
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minecraft_network

  backend:
    build:
      context: ./tfg
    container_name: tfg_backend
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/minecraft_project
      SPRING_DATASOURCE_USERNAME: pingu
      SPRING_DATASOURCE_PASSWORD: miausita25
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    command: mvn spring-boot:run
    networks:
      - minecraft_network

  frontend:
    image: nginx:stable-alpine
    container_name: tfg_frontend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 1) Configuración de Nginx (HTTP y HTTPS)
      - ./tfg_web/default.conf:/etc/nginx/conf.d/default.conf:ro

      # 2) Archivos estáticos de tu SPA
      - ./tfg_web/dist:/usr/share/nginx/html:ro

      # 3) Certificados y snippets SSL completos de Certbot
      - ./certbot/etc:/etc/letsencrypt:ro

      # 4) Retos ACME para renovación
      - ./certbot/www:/var/www/certbot:ro

    networks:
      - minecraft_network

volumes:
  postgres_data:

networks:
  minecraft_network:
    external: true
