version: '3.8'  # Versión de Docker Compose

services:
  postgres:  # Nombre del servicio
    image: postgres:alpine  # Imagen de PostgreSQL
    container_name: postgres_db  # Nombre del contenedor
    environment:
      POSTGRES_USER: pingu  # Usuario de la base de datos
      POSTGRES_PASSWORD: miausita25  # Contraseña del usuario
      POSTGRES_DB: minecraft_project # Nombre de la base de datos
    ports:
      - "5433:5432"  # Mapeo de puertos (host:contenedor)
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volumen para persistir datos

volumes:
  postgres_data:  # Define un volumen para persistir los datos de PostgreSQL