name: CI/CD Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build & Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install local Cubiomes JAR
      - name: Install local Cubiomes JAR
        run: |
          mvn install:install-file \
            -Dfile=tfg/libs/cubiomes-java-0.0.6.jar \
            -DgroupId=com.rasmusantons \
            -DartifactId=cubiomes-java \
            -Dversion=0.0.6 \
            -Dpackaging=jar

      # ───────────────────────────────────────────────────────────
      # ←←← Insertamos SETUP-JAVA antes de cualquier mvn compile!  →→→
      # 3. Set up Java 21 (Temurin)
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      # 4. Build backend
      - name: Build backend
        run: mvn -B -DskipTests clean package -f tfg/pom.xml

      # 5. Build frontend
      - name: Build frontend
        run: |
          cd tfg_web
          npm ci
          npm run build

      # 6. Set up SSH key
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 7. (Optional) Test SSH connectivity
      - name: Test SSH connectivity
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa \
            ubuntu@${{ secrets.EC2_HOST }} "echo SSH OK"

      # 8. Deploy on EC2 via Git pull
      - name: Deploy on EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd ~/tfg/TFG-Myke
            git pull origin main

            # Rebuild on the server
            mvn -B -DskipTests clean package -f tfg/pom.xml
            cd tfg_web && npm ci && npm run build
            cd ..

            docker compose down
            docker compose up -d --build
          EOF
